default:
  image: node:20

stages:
  - lint
  - publish

variables:
  NPM_TOKEN: $CI_JOB_TOKEN

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - pnpm config set store-dir .pnpm-store

lint:
  stage: lint
  script:
    - pnpm install
    - pnpm run lint
  only:
    - merge_requests
    - branches

publish:
  stage: publish
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - echo "@scope:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - pnpm publish
  only:
    - tags
